import { AgeRangeEnum, GenderEnum, StageOfLifeEnum, TimeSlots } from "@/enums/app.enum";

export enum CategoryEnum {
  AMUSEMENT_PARK = 1,
  ART_GALLERY = 2,
  MOVIE_THEATER = 3,
  MUSEUM = 4,
  WATER_PARK = 5,
  ZOO = 6,
  HEALTH_AND_BEAUTY_SERVICE_MALE = 7,
  HEALTH_AND_BEAUTY_SERVICE_FEMALE = 8,
  BAKERY = 9,
  CAFE = 10,
  RESTAURANTS = 11,
  PARK = 12,
  SCHOOL_COLLEGES = 13,
  GROCERY_STORE = 14,
  GYM_STUDIO = 15,
  SHOPPING_MALL = 16,
  YOGA = 17,
  HIKING_TRAIL = 18,
  CLUBS = 19,
  BREAKFAST_SPOT = 21,
  NIGHT_MARKET = 22,
  LANDMARK_AND_OUTDOORS = 23,
  BAR = 24,
}

const activityCategorizationSchema = {
  [TimeSlots.MORNING]: [
    {
      label: "Gym and Studio",
      id: CategoryEnum.GYM_STUDIO,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY, AgeRangeEnum.FORTY_ONE_TO_FIFTY],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Go for a hike",
      id: CategoryEnum.HIKING_TRAIL,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Yoga",
      id: CategoryEnum.YOGA,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
  ],
  [TimeSlots.LATE_MORNING]: [
    {
      label: "Go get some coffee",
      id: CategoryEnum.CAFE,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Get some breakfast",
      id: CategoryEnum.BREAKFAST_SPOT,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Explore a nearby park",
      id: CategoryEnum.PARK,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Explore nearby meuseum",
      id: CategoryEnum.MUSEUM,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
  ],
  [TimeSlots.AFTERNOON]: [
    {
      label: "Visit an Art Gallery",
      id: CategoryEnum.ART_GALLERY,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Visit a Zoo",
      id: CategoryEnum.ZOO,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Have some fun at a amusement park",
      id: CategoryEnum.AMUSEMENT_PARK,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY, AgeRangeEnum.FORTY_ONE_TO_FIFTY],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Go to water park",
      id: CategoryEnum.WATER_PARK,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY, AgeRangeEnum.FORTY_ONE_TO_FIFTY],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Visit Shopping Mall",
      id: CategoryEnum.SHOPPING_MALL,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Restaurant",
      id: CategoryEnum.RESTAURANTS,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "School and Colleges",
      id: CategoryEnum.SCHOOL_COLLEGES,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY],
      stageOfLife: [StageOfLifeEnum.MARRIED_WITH_KIDS],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Go to a Saloon",
      id: CategoryEnum.HEALTH_AND_BEAUTY_SERVICE_FEMALE,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY],
      stageOfLife: [
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.OTHER],
    },
    {
      label: "Go to a Saloon",
      id: CategoryEnum.HEALTH_AND_BEAUTY_SERVICE_MALE,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY],
      stageOfLife: [
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
      ],
      genderPreferences: [GenderEnum.MALE],
    },
    {
      label: "Go get some groceries",
      id: CategoryEnum.GROCERY_STORE,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Visit nearby landmarks",
      id: CategoryEnum.LANDMARK_AND_OUTDOORS,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
  ],
  [TimeSlots.EVENING]: [
    {
      label: "Restaurant",
      id: CategoryEnum.RESTAURANTS,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Night Market",
      id: CategoryEnum.NIGHT_MARKET,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Bar",
      id: CategoryEnum.BAR,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY, AgeRangeEnum.FORTY_ONE_TO_FIFTY],
      stageOfLife: [StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS, StageOfLifeEnum.MARRIED_OR_PARTNERED],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Night Club",
      id: CategoryEnum.CLUBS,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY, AgeRangeEnum.FORTY_ONE_TO_FIFTY],
      stageOfLife: [StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS, StageOfLifeEnum.MARRIED_OR_PARTNERED],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Movie Theater",
      id: CategoryEnum.MOVIE_THEATER,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
    {
      label: "Go for a evening walks",
      id: CategoryEnum.PARK,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE, GenderEnum.OTHER],
    },
  ],
};

export default activityCategorizationSchema;
