import { AgeRangeEnum, GenderEnum, StageOfLifeEnum, TimeSlots } from "@/enums/app.enum";

export enum CategoryEnum {
  AMUSEMENT_PARK = 1,
  ART_GALLERY = 2,
  MOVIE_THEATER = 3,
  MUSEUM = 4,
  WATER_PARK = 5,
  ZOO = 6,
  HEALTH_AND_BEAUTY_SERVICE_MALE = 7,
  HEALTH_AND_BEAUTY_SERVICE_FEMALE = 8,
  BAKERY = 9,
  CAFE = 10,
  RESTAURANTS = 11,
  PARK = 12,
  SCHOOL_COLLEGES = 13,
  GROCERY_STORE = 14,
  GYM_STUDIO = 15,
  SHOPPING_MALL = 16,
  YOGA = 17,
  HIKING_TRAIL = 18,
  CLUBS = 19,
  BREAKFAST_SPOT = 21,
  NIGHT_MARKET = 22,
  LANDMARK_AND_OUTDOORS = 23,
  BAR = 24,
}

const activityCategorizationSchema = {
  [TimeSlots.MORNING]: [
    {
      label: "Hit the Gym or Studio",
      id: CategoryEnum.GYM_STUDIO,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY, AgeRangeEnum.FORTY_ONE_TO_FIFTY],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Enjoy a Morning Hike",
      id: CategoryEnum.HIKING_TRAIL,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Relax with Morning Meditation",
      id: CategoryEnum.PARK,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Join a Yoga Session",
      id: CategoryEnum.YOGA,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
  ],
  [TimeSlots.LATE_MORNING]: [
    {
      label: "Grab a Coffee",
      id: CategoryEnum.CAFE,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Treat Yourself to Breakfast",
      id: CategoryEnum.BREAKFAST_SPOT,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Discover a Nearby Park",
      id: CategoryEnum.PARK,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Explore a Museum",
      id: CategoryEnum.MUSEUM,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
  ],
  [TimeSlots.AFTERNOON]: [
    {
      label: "Check Out an Art Gallery",
      id: CategoryEnum.ART_GALLERY,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Visit the Zoo",
      id: CategoryEnum.ZOO,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Have Fun at an Amusement Park",
      id: CategoryEnum.AMUSEMENT_PARK,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY, AgeRangeEnum.FORTY_ONE_TO_FIFTY],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Cool Off at a Water Park",
      id: CategoryEnum.WATER_PARK,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY, AgeRangeEnum.FORTY_ONE_TO_FIFTY],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Go Shopping at a Mall",
      id: CategoryEnum.SHOPPING_MALL,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Dine at a Restaurant",
      id: CategoryEnum.RESTAURANTS,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Visit a School or College",
      id: CategoryEnum.SCHOOL_COLLEGES,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY],
      stageOfLife: [StageOfLifeEnum.MARRIED_WITH_KIDS],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Pamper Yourself at a Salon",
      id: CategoryEnum.HEALTH_AND_BEAUTY_SERVICE_FEMALE,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY],
      stageOfLife: [
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
      ],
      genderPreferences: [GenderEnum.FEMALE],
    },
    {
      label: "Get Groomed at a Salon",
      id: CategoryEnum.HEALTH_AND_BEAUTY_SERVICE_MALE,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY],
      stageOfLife: [
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
      ],
      genderPreferences: [GenderEnum.MALE],
    },
    {
      label: "Stock Up at the Grocery Store",
      id: CategoryEnum.GROCERY_STORE,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Check Out Local Landmarks",
      id: CategoryEnum.LANDMARK_AND_OUTDOORS,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
  ],
  [TimeSlots.EVENING]: [
    {
      label: "Dine at a Restaurant",
      id: CategoryEnum.RESTAURANTS,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Stroll Through a Night Market",
      id: CategoryEnum.NIGHT_MARKET,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Unwind at a Bar",
      id: CategoryEnum.BAR,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY, AgeRangeEnum.FORTY_ONE_TO_FIFTY],
      stageOfLife: [StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS, StageOfLifeEnum.MARRIED_OR_PARTNERED],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Dance the Night Away at a Club",
      id: CategoryEnum.CLUBS,
      ageGroup: [AgeRangeEnum.EIGHTEEN_TO_THIRTY, AgeRangeEnum.THIRTY_ONE_TO_FORTY, AgeRangeEnum.FORTY_ONE_TO_FIFTY],
      stageOfLife: [StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS, StageOfLifeEnum.MARRIED_OR_PARTNERED],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Watch a Movie",
      id: CategoryEnum.MOVIE_THEATER,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
    {
      label: "Take a Relaxing Evening Walk",
      id: CategoryEnum.PARK,
      ageGroup: [
        AgeRangeEnum.EIGHTEEN_TO_THIRTY,
        AgeRangeEnum.THIRTY_ONE_TO_FORTY,
        AgeRangeEnum.FORTY_ONE_TO_FIFTY,
        AgeRangeEnum.FIFTY_ONE_TO_SIXTY,
        AgeRangeEnum.SIXTY_PLUS,
      ],
      stageOfLife: [
        StageOfLifeEnum.SINGLE_AND_EXPLORING_OPTIONS,
        StageOfLifeEnum.MARRIED_OR_PARTNERED,
        StageOfLifeEnum.MARRIED_WITH_KIDS,
        StageOfLifeEnum.RETIRED_AND_ENJOYING_LIFE,
      ],
      genderPreferences: [GenderEnum.FEMALE, GenderEnum.MALE],
    },
  ],
};

export default activityCategorizationSchema;
