name: Formatting, Linting and Type Check

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  code-sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies (Normal Mode)
        run: pnpm install

      - name: Format Check with Prettier
        run: pnpm run format:check

      - name: Lint Check with ESLint
        run: pnpm lint

      - name: Type Check with TypeScript
        run: pnpm run type:check

      - name: Feedback
        run: echo "Formatting, linting and type check passed"
